### ISSUE TITLE
Use Web Activity to launch Marketplace rating

### ISSUE THREAD

**Issue by digitarald** [dcoloma/fxosRate#12]
Marketplace allows ratings via Web Activity: https://github.com/mozilla/fireplace/wiki/Web-Activities#marketplace-app-rating

As the current behavior isn't perfect I also filed https://bugzilla.mozilla.org/show_bug.cgi?id=1164072 to have the rating window show inline and to get a return value.

**Comment by dcoloma** [comment]
This should be fixed at https://github.com/dcoloma/fxosRate/commit/a2343660d607fad4d77b384e803826b31c5edbb7
